/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SlidesRouteImport } from './routes/slides'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as CalibrationRouteImport } from './routes/calibration'
import { Route as AnalyzerRouteImport } from './routes/analyzer'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SlidesRoute = SlidesRouteImport.update({
  id: '/slides',
  path: '/slides',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const CalibrationRoute = CalibrationRouteImport.update({
  id: '/calibration',
  path: '/calibration',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzerRoute = AnalyzerRouteImport.update({
  id: '/analyzer',
  path: '/analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analyzer': typeof AnalyzerRoute
  '/calibration': typeof CalibrationRoute
  '/guide': typeof GuideRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/slides': typeof SlidesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analyzer': typeof AnalyzerRoute
  '/calibration': typeof CalibrationRoute
  '/guide': typeof GuideRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/slides': typeof SlidesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analyzer': typeof AnalyzerRoute
  '/calibration': typeof CalibrationRoute
  '/guide': typeof GuideRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/slides': typeof SlidesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analyzer'
    | '/calibration'
    | '/guide'
    | '/sitemap.xml'
    | '/slides'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/analyzer'
    | '/calibration'
    | '/guide'
    | '/sitemap.xml'
    | '/slides'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analyzer'
    | '/calibration'
    | '/guide'
    | '/sitemap.xml'
    | '/slides'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalyzerRoute: typeof AnalyzerRoute
  CalibrationRoute: typeof CalibrationRoute
  GuideRoute: typeof GuideRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SlidesRoute: typeof SlidesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/slides': {
      id: '/slides'
      path: '/slides'
      fullPath: '/slides'
      preLoaderRoute: typeof SlidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calibration': {
      id: '/calibration'
      path: '/calibration'
      fullPath: '/calibration'
      preLoaderRoute: typeof CalibrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyzer': {
      id: '/analyzer'
      path: '/analyzer'
      fullPath: '/analyzer'
      preLoaderRoute: typeof AnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalyzerRoute: AnalyzerRoute,
  CalibrationRoute: CalibrationRoute,
  GuideRoute: GuideRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SlidesRoute: SlidesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
